FROM python:3.13-slim

COPY requirements.txt requirements.txt
RUN python3 -m pip install -r requirements.txt

COPY . /app
WORKDIR /app

ENTRYPOINT ["python3", "-m", "uvicorn",  "--host", "0.0.0.0", "main:app"]
