FROM python:3.9-slim

COPY . /app
WORKDIR /app
RUN apt-get update \
    && apt-get install -y git \
    # Clean up
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*
RUN python3 -m pip install -r /app/requirements.txt
RUN rm -rf /root/.cache
ENTRYPOINT ["python3", "-m", "uvicorn",  "--host", "0.0.0.0", "main:app"]
