version: "2"

services:
  awsl-mysql:
    image: mysql
    container_name: awsl-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: awsl
      MYSQL_USER: admin
      MYSQL_PASSWORD: cXFxcXFxcXExCg==
      MYSQL_ROOT_PASSWORD: cXFxcXFxcXExCg==
    ports:
      - "9306:3306"
